#!/usr/bin/env python
from fabric.main import main

from stowaway import fabfile

if __name__ == '__main__':
    path = fabfile.__file__
    if path.endswith('c'):
        path = path[:-1]
    main([path])

